# Generated by Django 3.0.4 on 2020-03-18 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('phone_no', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('spec', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('phone_no', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('speciality', models.ForeignKey(db_column='spec', on_delete=django.db.models.deletion.CASCADE, to='signup_login.Speciality')),
            ],
        ),
    ]
