# Generated by Django 3.0.4 on 2020-03-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
