# Generated by Django 3.0.4 on 2020-03-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='seen_by_first',
            field=models.CharField(blank=True, default='n', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='seen_by_second',
            field=models.CharField(blank=True, default='n', max_length=1, null=True),
        ),
    ]
